{
 "title": "节点监控",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(node_cpu_core_num{}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU 核心数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_core_num{hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "总内存",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_total_bytes{hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "可用内存",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_total_bytes{hostname=~\"$hostname\"}-node_memory_usage_bytes{hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_cpu_usage_percent{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_usage_bytes{hostname=~\"$hostname\"}",
     "legendFormat": "{{  hostname }}"
    }
   ]
  }
 ]
}