---
  image: "prom/prometheus:v2.23.0"
  volumes: 
    - "/opt/oars/worker/data/system/prometheus/data:/prometheus"
  command: 
    - "--storage.tsdb.path=/prometheus"
    - "--config.file=/etc/prometheus/prometheus.yml"
  configmap: 
    /etc/prometheus/prometheus.yml: |-
      global:
        scrape_interval:     15s
        evaluation_interval: 15s
      scrape_configs:
      - job_name: node
        dns_sd_configs:
        - names:
          - node.system
          type: A
          port: 8803
                  
